export const TEST_CALENDAR = {
  year: '2022',
  month: 'November',
  days: [
    {
      $date: new Date(2022, 9, 31),
      date: '31/10/2022',
      day: '31',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 1),
      date: '01/11/2022',
      day: '01',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 2),
      date: '02/11/2022',
      day: '02',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 3),
      date: '03/11/2022',
      day: '03',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 4),
      date: '04/11/2022',
      day: '04',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 5),
      date: '05/11/2022',
      day: '05',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 6),
      date: '06/11/2022',
      day: '06',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 7),
      date: '07/11/2022',
      day: '07',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 8),
      date: '08/11/2022',
      day: '08',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 9),
      date: '09/11/2022',
      day: '09',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 10),
      date: '10/11/2022',
      day: '10',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 11),
      date: '11/11/2022',
      day: '11',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 12),
      date: '12/11/2022',
      day: '12',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 13),
      date: '13/11/2022',
      day: '13',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 14),
      date: '14/11/2022',
      day: '14',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 15),
      date: '15/11/2022',
      day: '15',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 16),
      date: '16/11/2022',
      day: '16',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 17),
      date: '17/11/2022',
      day: '17',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 18),
      date: '18/11/2022',
      day: '18',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 19),
      date: '19/11/2022',
      day: '19',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 20),
      date: '20/11/2022',
      day: '20',
      currentDisplayedMonth: true,
      isToday: true,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 21),
      date: '21/11/2022',
      day: '21',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 22),
      date: '22/11/2022',
      day: '22',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 23),
      date: '23/11/2022',
      day: '23',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 24),
      date: '24/11/2022',
      day: '24',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 25),
      date: '25/11/2022',
      day: '25',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 26),
      date: '26/11/2022',
      day: '26',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 27),
      date: '27/11/2022',
      day: '27',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 28),
      date: '28/11/2022',
      day: '28',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 29),
      date: '29/11/2022',
      day: '29',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 10, 30),
      date: '30/11/2022',
      day: '30',
      currentDisplayedMonth: true,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 1),
      date: '01/12/2022',
      day: '01',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 2),
      date: '02/12/2022',
      day: '02',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 3),
      date: '03/12/2022',
      day: '03',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 4),
      date: '04/12/2022',
      day: '04',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 5),
      date: '05/12/2022',
      day: '05',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 6),
      date: '06/12/2022',
      day: '06',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 7),
      date: '07/12/2022',
      day: '07',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 8),
      date: '08/12/2022',
      day: '08',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 9),
      date: '09/12/2022',
      day: '09',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 10),
      date: '10/12/2022',
      day: '10',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
    {
      $date: new Date(2022, 11, 11),
      date: '11/12/2022',
      day: '11',
      currentDisplayedMonth: false,
      isToday: false,
      isSelected: false,
      inRange: false,
      isRangeStart: false,
      isRangeEnd: false,
      willBeInRange: false,
    },
  ],
};
