export const TEST_MONTHS = [
  {
    $date: new Date(2022, 0, 1),
    name: 'January',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 1, 1),
    name: 'February',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 2, 1),
    name: 'March',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 3, 1),
    name: 'April',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 4, 1),
    name: 'May',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 5, 1),
    name: 'June',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 6, 1),
    name: 'July',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 7, 1),
    name: 'August',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 8, 1),
    name: 'September',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 9, 1),
    name: 'October',
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 10, 1),
    name: 'November',
    active: true,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 11, 1),
    name: 'December',
    active: false,
    selected: false,
    disabled: false,
  },
];
