export const TEST_YEARS = [
  {
    $date: new Date(2019, 10, 20),
    value: 2019,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2020, 10, 20),
    value: 2020,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2021, 10, 20),
    value: 2021,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2022, 10, 20),
    value: 2022,
    isActive: true,
    isSelected: false,
    active: true,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2023, 10, 20),
    value: 2023,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2024, 10, 20),
    value: 2024,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2025, 10, 20),
    value: 2025,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2026, 10, 20),
    value: 2026,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2027, 10, 20),
    value: 2027,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2028, 10, 20),
    value: 2028,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2029, 10, 20),
    value: 2029,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
  {
    $date: new Date(2030, 10, 20),
    value: 2030,
    isActive: false,
    isSelected: false,
    active: false,
    selected: false,
    disabled: false,
  },
];
