name: e2e Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "*"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i
    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
    - name: Install app dependencies
      run: pnpm e2e
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
